commiting index page of quiz app
rajaranjanmr/quiz_app_ pull request #1
Opened 2022-02-16 21:48 UTC by rajaranjanmr

2022-02-17 05:44 UTC, sri-rishi requested changes
![image](https://user-images.githubusercontent.com/72429483/154412934-15022676-214e-4ead-bad7-9f2e45997dfe.png)

I think you should work with colors UI is not looking good, and card are not centered

2022-02-17 05:54 UTC, sri-rishi requested changes

2022-02-17 05:54 UTC, sri-rishi commented on index.css
> +
remove all  extra spacing from code

2022-02-17 05:54 UTC, sri-rishi commented on index.css
> +    /* position: relative; */
remove all comments

2022-02-17 05:54 UTC, sri-rishi commented on index.css
> +    background-color: #612897;
use variable color naming

2022-02-17 06:04 UTC, Anurag021 commented on index.js
> +}
there are 2 different variations of defining functions (i.e. arrow(=>), and function) try to follow the same standard,
I guess arrow one would be fine here

2022-02-17 06:07 UTC, Anurag021 approved these changes
I believe specific use of theme in color would look better on UI, and try to make use of variables for color that would bring uniformity to the code, rest looks good.

2022-02-18 06:02 UTC, sri-rishi approved these changes

2022-02-18 06:04 UTC, merged