adding questions page
rajaranjanmr/quiz_app_ pull request #5
Opened 2022-02-18 18:18 UTC by rajaranjanmr

2022-02-18 19:54 UTC, sri-rishi requested changes
![image](https://user-images.githubusercontent.com/72429483/154752399-de90eebb-ea41-4cf6-a7c8-6917f3ea37f6.png)

Give cards padding of margin from bottom

2022-02-19 05:43 UTC, sri-rishi approved these changes

2022-02-20 15:21 UTC, mmanjuprasad approved these changes
The app looks good

U can use some light colored bg instead of orange
as it is too vibrant for eyes

2022-02-20 15:21 UTC, mmanjuprasad commented on index.css
> -    background-color: red;
u can add color variable in root and use it here

2022-02-20 17:19 UTC, merged